INSERT ALL
INTO AREAS (AREA,ID_USUARIO,ID_ROL,REGISTRO) VALUES ('','',0,TO_DATE(SYSDATE,'DD-MM-YYYY HH:MI:SS AM'))
INTO AREAS (AREA,ID_USUARIO,ID_ROL,REGISTRO) VALUES ('','',0,TO_DATE(SYSDATE,'DD-MM-YYYY HH:MI:SS AM'))
INTO AREAS (AREA,ID_USUARIO,ID_ROL,REGISTRO) VALUES ('','',0,TO_DATE(SYSDATE,'DD-MM-YYYY HH:MI:SS AM'))
SELECT * FROM dual;