INSERT ALL
INTO ROLES (ROL,REGISTRO) VALUES ('',TO_DATE(SYSDATE,'DD-MM-YYYY HH:MI:SS AM'))
INTO ROLES (ROL,REGISTRO) VALUES ('',TO_DATE(SYSDATE,'DD-MM-YYYY HH:MI:SS AM'))
INTO ROLES (ROL,REGISTRO) VALUES ('',TO_DATE(SYSDATE,'DD-MM-YYYY HH:MI:SS AM'))
SELECT * FROM dual;