import {FaHome,/*FaAngleDown,*/FaAngleRight} from 'react-icons/fa'
export const menu=[
    {
        "encabezado":"Inicio",
        "subItems":[
            {
                "nombre":"My profile",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "subMenu":[
                    {
                        "nombre":"My1",
                        "hreff":"/page"
                    },
                    {
                        "nombre":"My2",
                        "hreff":"/page"
                    },
                    {
                        "nombre":"My3",
                        "hreff":"/page"
                    },
                    {
                        "nombre":"My4",
                        "hreff":"/page"
                    },
                    {
                        "nombre":"My5",
                        "hreff":"/page"
                    }]
            },
            {
                "nombre":"Settings",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "subMenu":[{"nombre":"S1","hreff":"/page"},{"nombre":"S2","hreff":"/page"}]
            },
            {
                "nombre":"Friends",
                "leftIcon":"",
                "rightIcon":<FaHome/>,
                "hreff":"/page",
                "subMenu":""
            }
        ],
        "icon":<FaAngleRight/>,
        "hreff":"#"
    },
    {
        "encabezado":"Inicio2",
        "subItems":[
            {
                "nombre":"uno",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "subMenu":[{"nombre":"Option1","hreff":"/page"},{"nombre":"Option2","hreff":"/page"}]
            },
            {
                "nombre":"dos",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"/page",
                "subMenu":""
            },
            {
                "nombre":"tres",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"/page",
                "subMenu":""
            }
        ],
        "icon":<FaAngleRight/>,
        "hreff":"#"
    },
    {
        "encabezado":"Inicio3",
        "subItems":[
            {
                "nombre":"uno",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"/page",
                "subMenu":""
            },
            {
                "nombre":"dos",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"/page",
                "subMenu":""
            },
            {
                "nombre":"tres",
                "leftIcon":"",
                "rightIcon":"",
                "hreff":"/page",
                "subMenu":""
            }
        ],
        "icon":"",
        "hreff":"#"
    },
    {
        "encabezado":"Inicio4",
        "subItems":"",
        "icon":"",
        "hreff":"/page"
    }
];