import {FaHome,/*FaAngleDown,*/FaAngleRight} from 'react-icons/fa'
export const menu=[
    {
        "encabezado":"Inicio",
        "contenido":"",
        "subItems":[
            {
                "nombre":"My profile",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":"",
                "subMenu":[
                    {
                        "nombre":"My1",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>My1</h1>
                        </>
                    },
                    {
                        "nombre":"My2",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>My2</h1>
                        </>
                    },
                    {
                        "nombre":"My3",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>My3</h1>
                        </>
                    },
                    {
                        "nombre":"My4",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>My4</h1>
                        </>
                    },
                    {
                        "nombre":"My5",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>My5</h1>
                        </>
                    }]
            },
            {
                "nombre":"Settings",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":"",
                "subMenu":[
                    {
                        "nombre":"S1",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>S1</h1>
                        </>
                    },
                    {
                        "nombre":"S2",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>S2</h1>
                        </>
                    }
                ]
            },
            {
                "nombre":"Friends",
                "leftIcon":"",
                "rightIcon":<FaHome/>,
                "hreff":"#",
                "contenido":
                    <>
                        <h1>Friends</h1>
                    </>,
                "subMenu":""
            }
        ],
        "icon":<FaAngleRight/>,
        "hreff":"#"
    },
    {
        "encabezado":"Inicio2",
        "contenido":"",
        "subItems":[
            {
                "nombre":"uno",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":"",
                "subMenu":[
                    {
                        "nombre":"Option1",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>Option1</h1>
                        </>
                    },
                    {
                        "nombre":"Option2",
                        "hreff":"#",
                        "contenido":
                        <>
                            <h1>Option2</h1>
                        </>
                    }
                ]
            },
            {
                "nombre":"dos",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":
                <>
                    <h1>dos</h1>
                </>,
                "subMenu":""
            },
            {
                "nombre":"tres",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":
                <>
                    <h1>tres</h1>
                </>,
                "subMenu":""
            }
        ],
        "icon":<FaAngleRight/>,
        "hreff":"#"
    },
    {
        "encabezado":"Inicio3",
        "contenido":"",
        "subItems":[
            {
                "nombre":"uno",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":
                <>
                    <h1>Uno</h1>
                </>,
                "subMenu":""
            },
            {
                "nombre":"dos",
                "leftIcon":"",
                "rightIcon":<FaAngleRight/>,
                "hreff":"#",
                "contenido":
                <>
                    <h1>Dos</h1>
                </>,
                "subMenu":""
            },
            {
                "nombre":"tres",
                "leftIcon":"",
                "rightIcon":"",
                "hreff":"#",
                "contenido":
                <>
                    <h1>Tres</h1>
                </>,
                "subMenu":""
            }
        ],
        "icon":"",
        "hreff":"#"
    },
    {
        "encabezado":"Inicio4",
        "contenido": 
            <>
                <h1>Inicio4</h1>
            </>,
        "subItems":"",
        "icon":"",
        "hreff":"#"
    }
];